baseURL = "/"
languageCode = "en-us"
title = "Daniel Santiago"
theme = "hugo-them-nix"
GoogleAnalytics = "UA-112069650-1"

[menu]
  [[menu.header]]
    name = "Post"
    weight = 0
    url = "/post"
  [[menu.header]]
    name = "Acerca de"
    weight = 1
    url = "/about"

[params]
  GithubID = "santiago02"
  TwitterID = "your_twitter"
  LinkedInID = "your_linkedin"
  GoogleplusID = "your_googleplus"
  FacebookID = "your_facebook"
  Name = "Daniel Santiago"
  HeaderUsername = "Daniel"
  HeaderHostname = "Daniel"
  Email = "hello@danielsantiago.com.mx"
  About = "Hola soy Daniel Santiago, co-fundador de nelli.tech"
  ProfilePicture = "/daniel.png"
  SlackURL = "your_slack_invite_url"