baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
[params]
  GnuPGFingerprint = "your_gpg_fingerprint"
  StackExchangeID = "your_stackexchange_id"
  StackOverflowID = "your_stackoverflow_id"
  GithubID = "your_github"
  GitlabId = "your_gitlab"
  BitbucketID = "your_bitbucket_id"
  TwitterID = "your_twitter"
  CodepenID = "your_codepen"
  LinkedInID = "your_linkedin"
  GoogleplusID = "your_googleplus"
  FacebookID = "your_facebook"
  InstagramID = "your_instagram"
  TelegramID = "your_telegram"
  Name = "your_name"
  HeaderUsername = "username"
  HeaderHostname = "hostname"
  Email = "your_email"
  About = "info_about_you"
  ProfilePicture = "profile_picture_url"
  GoogleAnalytics = "your_google_analytics_id"
  SlackURL = "https://join.slack.com/..."
  PayPalMeID = "https://www.paypal.me/..."
  XingURL = "https://www.xing.com/profile/..."
[menu]
  [[menu.header]]
    name = "posts"
    weight = 0
    url = "/posts"