baseURL = "/"
languageCode = "en-us"
title = "Daniel Santiago"
theme = "hugo-them-nix"
[menu]
  [[menu.header]]
    name = "POST"
    weight = 0
    url = "/post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "/about"

[params]
  GithubID = "https://github.com/santiago02"
  TwitterID = "your_twitter"
  LinkedInID = "your_linkedin"
  GoogleplusID = "your_googleplus"
  FacebookID = "your_facebook"
  Name = "Daniel Santiago"
  HeaderUsername = "hugo"
  HeaderHostname = "hugo"
  Email = "hello@danielsantiago.com.mx"
  About = "Hola soy Daniel Santiago, co-fundador de nelli.tech"
  ProfilePicture = "/static/pictures/profile.png"
  SlackURL = "your_slack_invite_url"