baseURL = "/"
languageCode = "en-us"
theme = "hugo-them-nix"
title = "Daniel Santiago"
[[menu.header]]
name = "Acerca de"
url = "/about"
weight = 1
[[menu.header]]
name = "Post"
url = "/post"
weight = 0
[params]
about = "Hola soy Daniel Santiago, co-fundador de nelli.tech"
email = "hello@danielsantiago.com.mx"
facebookid = "daniel.santiago.94043"
githubid = "santiago02"
googleanalytics = "UA-112069650-1"
googleplusid = "your_googleplus"
headerhostname = "Daniel"
headerusername = "Daniel"
linkedinid = "33537192"
name = "Daniel Santiago"
profilepicture = "/daniel.png"
slackurl = "your_slack_invite_url"
twitterid = "dasr02"
GoogleAnalytics = "UA-112069650-1"

